spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lemall?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
    username: root
    password: root
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  redis:
    #配置redis
    database: 0
    host: 127.0.0.1
    port: 6379
#  servlet:
#    multipart:
#      max-request-size: 100m
#      max-file-size: 10m


logging:
  level:
    com:
      zzzl:
        lemall: debug



mybatis:
  mapper-locations: classpath:mappers/*Mapper.xml
  type-aliases-package: com.zzzl.lemall.domain
